name: Publish Docker image
on:
  release:
    types: [published]
jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: set up Ruby and Bundler
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.6
      - name: Run InSpec tests on local image
        run: bundle && bundle exec rake test
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: digitalidentity/ishigaki:latest, digitalidentity/ishigaki:${{GITHUB_REF}}
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: digitalidentity/ishigaki:latest, digitalidentity/ishigaki:${{GITHUB_REF}}
